{
 "title": "dashboard_TrafficAnalyzer",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Загруженность/нарушения зон (люди в минуту)",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "epm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT   \r\n  zone_1 AS \"Zone 1\",\r\n  zone_2 AS \"Zone 2\",\r\n  zone_3 AS \"Zone 3\",\r\n  zone_4 AS \"Zone 4\",\r\n  zone_5 AS \"Zone 5\"\r\nFROM zone_info\r\nORDER BY timestamp DESC\r\nLIMIT 1;\r\n"
    }
   ]
  },
  {
   "title": "График изменения загруженности/нарушения зон",
   "type": "timeseries",
   "description": "число людей в минуту",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  zone_1 AS \"Zone 1\",\r\n  zone_2 AS \"Zone 2\",\r\n  zone_3 AS \"Zone 3\",\r\n  zone_4 AS \"Zone 4\",\r\n  zone_5 AS \"Zone 5\",\r\n  timestamp_date\r\nFROM\r\n  zone_info\r\nORDER BY timestamp_date DESC\r\n\r\n"
    }
   ]
  },
  {
   "title": "Число людей на участке видеосъемки",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT timestamp_date, persons FROM zone_info  "
    }
   ]
  }
 ]
}